# Generated by Django 3.2.11 on 2022-04-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusermodel',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=18, verbose_name='возраст'),
        ),
        migrations.AddField(
            model_name='myusermodel',
            name='city',
            field=models.CharField(blank=True, max_length=20, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='myusermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='myusermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
